### PR TITLE
add support for [pre|post][up|down] configuration

### PR DESCRIPTION
**Pull request by ghost**
This adds support for custom commands to be run at any state before and after the wireguard interface is created.

### CODE REVIEW

**Comment by spacedog** [comment]
Thank you for contributing? Don't you mind to add rspec checks for these new parameters?

**Comment by ghost** [comment]
Ah I'm sorry, of course! Does a change in `spec/defines/interface_spec.rb` suffice or is there another place where I should add new tests?

**Comment by spacedog** [comment]
`spec/defines/interface_spec.rb` is the right place. You also may need latest changes (#18 )to fix travis checks

**Comment by spacedog** [comment]
Closing as this has been implemented in #25

**Pull request closed without merging**
